name: Test
'on':
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 18.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install
        run: |
          yarn install --frozen-lockfile

      - name: Lint
        shell: bash
        run: |
          yarn run lint

      - name: Build
        shell: bash
        run: |
          yarn run build

      - name: Mocha tests
        shell: bash
        run: |
          yarn run test:mocha:ci

      - name: Install chromium dependencies
        if: ${{ matrix.node-version == '18.x' }}
        run: |
          sudo apt install libudev-dev libgtk2.0-0
          sudo ln -sf /lib/$(arch)-linux-gnu/libudev.so.1 /lib/$(arch)-linux-gnu/libudev.so.0

      - name: Install chromium
        if: ${{ matrix.node-version == '18.x' }}
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: 297097 # Chromium 39.0.2171.99 (Android - 5.1.0)

      - name: Karma tests
        if: ${{ matrix.node-version == '18.x' }}
        uses: GabrielBB/xvfb-action@v1
        env:
          CHROMIUM_BIN: /opt/hostedtoolcache/chromium/297097/x64/chrome
        with:
          run: |
            yarn run test:karma

      - name: Coveralls
        if: ${{ matrix.node-version == '18.x' }}
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        shell: bash
        run: |
          yarn add coveralls -D
          yarn run coveralls
